/**
 * Dashboard Route (/app/)
 *
 * Main dashboard page displaying all projects.
 * Fetches project data from the backend using React Query.
 */

import { CreateProjectDialog, ProjectsTable } from "@/components/app/dashboard";
import { createFileRoute } from "@tanstack/react-router";

// Import the generated React Query hook for fetching projects
import { useListProjectsFilesProjectsGet } from "@/api/generated/files/files";

export const Route = createFileRoute("/app/")({
	component: Dashboard,
});

function Dashboard() {
	// Fetch projects from the backend API
	// This hook is auto-generated by Orval from the OpenAPI spec
	const { data, isLoading, error } = useListProjectsFilesProjectsGet();

	// Extract the projects array from the response
	// The API returns a union of success (200) or error (422) response
	// We safely access .data which contains ProjectResponse[] on success
	const projects = data?.status === 200 ? data.data : [];

	return (
		<div className="container mx-auto p-6 md:p-12">
			{/* Header section with title and create button */}
			<div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
				<div>
					<h1 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-400 font-clash mb-2">
						Your Projects
					</h1>
					<p className="text-gray-400 font-mono text-sm">
						// Select a project to begin document preparation
					</p>
				</div>
				<CreateProjectDialog />
			</div>

			{/* Loading state */}
			{isLoading && (
				<div className="text-center py-12 text-gray-400 font-mono">
					Loading projects...
				</div>
			)}

			{/* Error state */}
			{error && (
				<div className="text-center py-12 text-red-400 font-mono">
					Error loading projects. Please try again.
				</div>
			)}

			{/* Projects table - only render when data is available */}
			{!isLoading && !error && <ProjectsTable data={projects} />}
		</div>
	);
}
