/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyUpdateFileCategoryFilesProjectsProjectIdFilesFileIdCategoryPut {
  /**
   * @minimum 1
   * @maximum 20
   */
  new_category_id: number;
  reasoning?: string;
  regenerate_pdf?: boolean;
}
