/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PDFUploadResponse {
  filename: string;
  content_type: string;
  message: string;
  location: string;
  project_id: number;
}
