/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectMemoryResponseClassificationsItem } from './projectMemoryResponseClassificationsItem';

/**
 * Response for getting project memory/results.
 */
export interface ProjectMemoryResponse {
  project_id: number;
  found: boolean;
  total_documents?: number;
  classifications?: ProjectMemoryResponseClassificationsItem[];
  merged_pdf_path?: string | null;
  timestamp?: string | null;
}
