/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProjectResponse {
  id: number;
  project_name: string;
  status: string;
  merged_pdf_path?: string | null;
  created_at: string;
  updated_at: string;
}
