/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result for a single file reclassification.
 */
export interface ReclassificationResultItem {
  file_id: number;
  old_category_id?: number | null;
  new_category_id: number;
  success: boolean;
  message: string;
}
