/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ReclassificationResultItem } from './reclassificationResultItem';

/**
 * Response for reclassification request.
 */
export interface ReclassificationResponse {
  project_id: number;
  success: boolean;
  message: string;
  prompt?: string | null;
  agent_reasoning?: string | null;
  total_updates: number;
  successful_updates: number;
  failed_updates: number;
  results: ReclassificationResultItem[];
  merged_pdf_regenerated?: boolean;
  merged_pdf_path?: string | null;
  download_url?: string | null;
}
