/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to reclassify files in a project.

This is the human-in-the-loop endpoint that allows changing
file categories after initial classification using natural language.
 */
export interface ReclassificationRequest {
  /**
   * Natural language instruction for reclassification. E.g., 'Move the bank statement PDF to category 3' or 'The document contract.pdf should be in employment category'
   * @minLength 5
   */
  prompt: string;
  /** Whether to regenerate the merged PDF after reclassification */
  regenerate_pdf?: boolean;
}
